### PR TITLE
Dockerfile to run in docker

### PR DESCRIPTION
**Pull request by ShaneMcC**
This should fix issue #6

Realistically, users are going to want to use docker-compose or so to actually run this and make it work and have mysql dbs etc, and it would be nice to put an example somewhere.

### CODE REVIEW

**Comment by greboid** [comment]
This doesn't have an alias for the resources, so won't be quite right yet

**Comment by tsumaru720** [comment]
Not issue 2 :)

**Comment by ShaneMcC** [comment]
Includes AliasMatch stuff now, and also appropriate config to make /conspectus/themes web-accessible.

**Comment by ShaneMcC** [comment]
Some quick testing instructions to help you:

```
# Run a throw-away database container (when you ctrl-c this it will vanish along with all the data)
docker run --name conspectus_db -e MYSQL_USER=assets -e MYSQL_PASSWORD=asdfsdf -e MYSQL_DATABASE=asset_tracker -e MYSQL_RANDOM_ROOT_PASSWORD=true --rm mysql:latest
# Watch and wait for that to be ready: [Server] /usr/sbin/mysqld: ready for connections

# Build the container
docker build --rm -t conspectus .

# Run the container
docker run --link conspectus_db -e SQL_HOSTNAME=conspectus_db --name conspectus_web -p 800:80 --rm conspectus

# Test at http://localhost:800/
```

**Pull request merged**
